---
title: Een spel kaarten
hero_image: images/banner.png
description: Maak een herbruikbaar objectgeoriënteerd model van een pak speelkaarten
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 4, design-0, programming-4, phys-comp-0, manufacture-0, community-0
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 4
last_tested: 2018-01-01
steps:
  - title: Inleiding
  - title: Wat heb je nodig
  - title: Creëer een class (klasse)
  - title: Een object instantiëren
  - title: Attributen en eigenschappen
  - title: 'Uitdaging: voeg een getter en setter toe'
  - title: Een spel kaarten
  - title: 'Uitdaging: wat nog meer?'
