---
title: Deck of cards
hero_image: images/banner.png
description: Create a reusable object oriented model of a deck of cards
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 4, design-0, programming-4, phys-comp-0, manufacture-0, community-0
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 4
last_tested: 2018-01-01
steps:
- title: Introduction
- title: What you will need
  completion: engaged
- title: Create a class
- title: Instantiate an object
- title: Attributes and properties
- title: 'Challenge: add a getter and setter'
- title: A deck of cards
  completion: internal
- title: 'Challenge: what else?'
