title: Deck of cards
hero_image: images/banner.png
description: Create a reusable object oriented model of a deck of cards
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 # possible values: 1, 2 or 3
listed: false
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-4, phys-comp-0, manufacture-0, community-0
interests: "games"
technologies: "python"
site_areas:
steps:
  - title: Introduction
  - title: What you will need
  - title: Create a class
  - title: Instantiate an object
